const { Profile } = require('../models');

const profileData = [
    {
        id: 2001,
        name: 'Jesse Beck',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1001,
    },
    {
        id: 2002,
        name: 'Nick Blanchard',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1002,
    },
    {
        id: 2003,
        name: 'Sam Bostack',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1003,
    },
    {
        id: 2004,
        name: 'Swain Brooks',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1004,
    },
    {
        id: 2005,
        name: 'Alex Brown',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1005,
    },
    {
        id: 2006,
        name: 'Simon Chavez',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1006,
    },
    {
        id: 2007,
        name: 'Xiema Chavez',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1007,
    },
    {
        id: 2008,
        name: 'Woody Clouse',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1008,
    },
    {
        id: 2009,
        name: 'Dave Coldiron',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1009,
    },
    {
        id: 2010,
        name: 'Troy Cook',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1010,
    },
    {
        id: 2011,
        name: 'Ray Cornell',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1011,
    },
    {
        id: 2012,
        name: 'Jorge Cuellar',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1012,
    },
    {
        id: 2013,
        name: 'Marc Demers',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1013,
    },
    {
        id: 2014,
        name: 'Michael DeVille',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1014,
    },
    {
        id: 2015,
        name: 'Mark Facey',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1015,
    },
    {
        id: 2016,
        name: 'Mackenzie Frey',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1016,
    },
    {
        id: 2017,
        name: 'Erik Garcia',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1017,
    },
    {
        id: 2018,
        name: 'Charles George',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1018,
    },
    {
        id: 2019,
        name: 'Dawson Goldfogel',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1019,
    },
    {
        id: 2020,
        name: 'Seth Goldfogel',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1020,
    },
    {
        id: 2021,
        name: 'Dave Hermann',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1021,
    },
    {
        id: 2022,
        name: 'Robert Hughes',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1022,
    },
    {
        id: 2023,
        name: 'Ben Hyman',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1023,
    },
    {
        id: 2024,
        name: 'Chase Imbert',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1024,
    },
    {
        id: 2025,
        name: 'Salveador Jimenez',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1025,
    },
    {
        id: 2026,
        name: 'Jacob Kingsford',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1026,
    },
    {
        id: 2027,
        name: 'Samuel Ramirez',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1027,
    },
    {
        id: 2028,
        name: 'Zack Leitz',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1028,
    },
    {
        id: 2029,
        name: 'David Logan',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1029,
    },
    {
        id: 2030,
        name: 'Bryce Logemann',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1030,
    },
    {
        id: 2031,
        name: 'Victor Manilla',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1031,
    },
    {
        id: 2032,
        name: 'Dylan Mattfeldt',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1032,
    },
    {
        id: 2033,
        name: 'Mark Matty',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1033,
    },
    {
        id: 2034,
        name: 'Jason Merrill',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1034,
    },
    {
        id: 2035,
        name: 'Scott Myatt',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1035,
    },
    {
        id: 2036,
        name: 'Alberto Olivias',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1036,
    },
    {
        id: 2037,
        name: 'Rich Owens',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1037,
    },
    {
        id: 2038,
        name: 'Zach Palmer',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1038,
    },
    {
        id: 2039,
        name: 'Nick Riffle',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1039,
    },
    {
        id: 2040,
        name: 'Anton Roberts',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1040,
    },
    {
        id: 2041,
        name: 'Ryan Rodgers',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1041,
    },
    {
        id: 2042,
        name: 'Chad Rutledge',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1042,
    },
    {
        id: 2043,
        name: 'Michael Sainz',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1043,
    },
    {
        id: 2044,
        name: 'CJ Sanders',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1044,
    },
    {
        id: 2045,
        name: 'Derek Schaeffer',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1045,
    },
    {
        id: 2046,
        name: 'Greg Schmitz',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1046,
    },
    {
        id: 2047,
        name: 'Erin Shireman',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1047,
    },
    {
        id: 2048,
        name: 'Mark Sikorski',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1048,
    },
    {
        id: 2049,
        name: 'Anna Sikorski',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1049,
    },
    {
        id: 2050,
        name: 'Lexie Sikorski',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1050,
    },
    {
        id: 2051,
        name: 'Laura Smith',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1051,
    },
    {
        id: 2052,
        name: 'Michiele Stapleton',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1052,
    },
    {
        id: 2053,
        name: 'Steve Strahler',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1053,
    },
    {
        id: 2054,
        name: 'Luis Torres',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1054,
    },
    {
        id: 2055,
        name: 'Paul Trani',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1055,
    },
    {
        id: 2056,
        name: 'Jorge Valencia',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1056,
    },
    {
        id: 2057,
        name: 'Khyathi Velpuri',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1057,
    },
    {
        id: 2058,
        name: 'Seshu Velpuri',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1058,
    },
    {
        id: 2059,
        name: 'Whitney Wantuck',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1059,
    },
    {
        id: 2060,
        name: 'Steve Wattz',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1060,
    },
    {
        id: 2061,
        name: 'Brady Yelverton',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1061,
    },
    {
        id: 2062,
        name: 'Joey Yelverton',
        singleRank: 1,
        doubleRank: 1,
        UserId: 1062,
    },
]

const seedProfiles = () => Profile.bulkCreate(profileData);

module.exports = seedProfiles;