const { User } = require('../models');
const CryptoJS = require('crypto-js');

require('dotenv').config();

let encryptedPassword = CryptoJS.AES.encrypt(
    'password',
    process.env.SECRET_KEY || '1234'
).toString();

const userData = [
    {
        id: 9999,
        email: 'cjsand03z@gmail.com',
        password: encryptedPassword,
        role: 'admin',
        active: true,
    },
    {
        id: 1001,
        // email: 'cj@cj.com',
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1002,
        // email: 'v@v.com',
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1003,
        // email: 'n@n.com',
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1004,
        // email: 'c@c.com',
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1005,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1006,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1007,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1008,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1009,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1010,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1011,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1012,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1013,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1014,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1015,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1016,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1017,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1018,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1019,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1020,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1021,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1022,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1023,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1024,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1025,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1026,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1027,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1028,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1029,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1030,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1031,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1032,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1033,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1034,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1035,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1036,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1037,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1038,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1039,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1040,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1041,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1042,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1043,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1044,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1045,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1046,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1047,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1048,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1049,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1050,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1051,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1052,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1053,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1054,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1055,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1056,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1057,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1058,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1059,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1060,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1061,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
    {
        id: 1062,
        password: encryptedPassword,
        role: 'player',
        active: true,
    },
]

const seedUsers = () => User.bulkCreate(userData);

module.exports = seedUsers;